#!/bin/sh

# $1 The game version 
# --- WOMNAM1A
# $2 source folder
# --- wolf_mountain
# $3 "game name"
# --- "Wolf Mountain"
# $4 part number
# --- 14E002
# $5 platform
# --- W4NAS07L
# $6 should be the market name
# --- currently only NorthAmerica, NewYork or LatinAmerica are supported
# $7 should be the source repository url all after http://reelteam6-services.ad.agi:18080/svn/EGMGameSoftware/SLV/
# --- 88Fortunes/branches/FB_WIP_iDeck/8LMSNA
# $8 can be an optional revision number

if [ $# -lt 6 ]; then
  echo "Usage: BuildSLVProduction <game version> <source folder> <"game name"> <part number> <platform> <market>"
  echo " -- available markets:"
  echo " NorthAmerica"
  echo " LatinAmerica"
  echo " NewYork"
  exit 2
fi
./set_platform.lua $5_Release
PLATFORMSIGFILE=/home/sgp1000/ProductionBuildLogs/$5.sig.txt
GAMEPLATFORMSIG="/home/sgp1000/Release/EGM/SLV/$6/$3 $1 $4/$5.txt"
GAMELOGFILE=/home/sgp1000/ProductionBuildLogs/$1/$1.build.txt
GAMESIGFILE="/home/sgp1000/Release/EGM/SLV/$6/$3 $1 $4/$1.txt"

if [ $6 == "NorthAmerica" ]; then
    MARKET="north_america_slv"
    elif [ $6 == "NewYork" ]; then
        MARKET="new_york"
    elif [ $6 == "LatinAmerica" ];then
        MARKET="latin_america"
    else
        echo "Invalid market specified"
        echo " -- available markets:"
        echo " NorthAmerica"
        echo " LatinAmerica"
        echo " NewYork"
        exit 12
fi

echo "Building "$3" on platform "$5" for "$6
cd /home/sgp1000/build/images/platform/P5/$5/games/egm/$1

echo "Cleaning..."

if [ -e /home/sgp1000/build/game_disk.img.gz ] ; then
    sudo rm -rf /home/sgp1000/build/game_disk.img.gz /home/sgp1000/build/deploy/games
fi

echo "Logging to directory /home/sgp1000/ProductionBuildLogs/"$1
mkdir /home/sgp1000/ProductionBuildLogs &> /dev/null
if [ -e /home/sgp1000/ProductionBuildLogs/$1 ]; then
    echo "Removing old logs"
    sudo rm -rf /home/sgp1000/ProductionBuildLogs/$1
fi
mkdir /home/sgp1000/ProductionBuildLogs/$1 &> /dev/null

echo "Starting Make..."
cd /home/sgp1000/build/images/platform/P5/$5/games/egm/$1
if [ -e .svn ]; then
    sudo rm -rf .svn
fi

make namerica_deploy-image &> /home/sgp1000/ProductionBuildLogs/$1/$1.build.txt
#/home/sgp1000/A2NAS01A_Release/images/platform/P5/A2NAS01A/games/egm/8LMSLV1A/images/namerica_deploy/
if [ -e /home/sgp1000/build/images/platform/P5/$5/games/egm/$1/images/namerica_deploy/$1-namerica_deploy.img.gz ]; then
    echo "Copying $1-namerica_deploy.img.gz to /home/sgp1000/ReleaseImages/ "
    if [ ! $8 == "" ]; then
        cp -f /home/sgp1000/build/images/platform/P5/$5/games/egm/$1/images/namerica_deploy/$1-namerica_deploy.img.gz /home/sgp1000/ReleaseImages/$1_$8-namerica_deploy.img.gz
    fi
    cp -f /home/sgp1000/build/images/platform/P5/$5/games/egm/$1/images/namerica_deploy/$1-namerica_deploy.img.gz /home/sgp1000/ReleaseImages/
    echo "$1-namerica_deploy.img.gz copy status: "$?
else
  echo "Build failed"
  exit 113
fi

sleep 60

echo "Generating document package for "$MARKET
cd /home/sgp1000/
./createPacket.lua $1 $2 "$3" $4 $MARKET $5 "1" $7 &> /home/sgp1000/ProductionBuildLogs/$1/$1.gen.txt

echo "Updating game signature document..."
cp -f $PLATFORMSIGFILE "$GAMEPLATFORMSIG"

echo -e "Game:"'\r\n'$1 $3'\r\n'$(grep -E "^sha1 generated:" $GAMELOGFILE)'\r\n'$(grep -E "^HMACsha1" $GAMELOGFILE) > "$GAMESIGFILE"

echo "Finished building "$3