#!/bin/bash
if [ $# -lt 1 ]; then
        echo "Usage: BuildPlatform <Platform Version> <market>" >&2
        exit 1
fi

CONFIG="${2}"

./checkLoop.lua
BUILD_PATH="/tools/bin:/mbtools/bin:/bin:/usr/bin:/sbin:/usr/sbin"

#./set_platform.lua $1_Release

LOGFILE=/home/sgp1000/ProductionBuildLogs/$1.build.txt 
SHA1LOG=/home/sgp1000/build/rootfs/logs/add_disk_security.log
SIGFILE=/home/sgp1000/ProductionBuildLogs/$1.sig.txt

echo "Building release platform..."
cd /home/sgp1000/build/images/platform/P5/$1

env -i PATH=$BUILD_PATH sudo make ${CONFIG}_deploy-image &> $LOGFILE"

if [ -e images/namerica_deploy/$1-namerica_deploy.img.gz ]; then
  echo "Copying image to /home/sgp1000/ReleaseImages/"
  cp -f images/namerica_deploy/$1-namerica_deploy.img.gz /home/sgp1000/ReleaseImages/$1-namerica_deploy.img.gz
  echo -e "Platform:"'\r\n'"$1"'\r\n'$(grep -E "^sha1 generated" $SHA1LOG)'\r\n'$(grep -E "^HMACsha1" $LOGFILE) > $SIGFILE 
  cd /home/sgp1000/
  sh /home/sgp1000/mountTM
  sh /home/sgp1000/copyReleaseImage $1-namerica_deploy.img.gz
else
  echo "Build failed - $1-namerica_deploy.img.gz was not created"
  exit 113
fi
