#!/bin/sh
# 1 - Build Type
# 2 - Build Parameters

BUILDTYPE="${1}"
BUILDPARAMS="${2}"

sh setup

echo " -- Removing old build output"
sudo rm -rf /home/sgp1000/buildOutput/*

echo " -- Writing buildParams.ini"
touch /home/sgp1000/sharedScripts/buildParams.ini
echo "${BUILDTYPE}" &> /home/sgp1000/sharedScripts/buildParams.ini
echo "${BUILDPARAMS}" &>> /home/sgp1000/sharedScripts/buildParams.ini
echo " -- buildParams.ini ready"

echo " -- Starting ${VMNAME}"
vmrun -T ws start /home/sgp1000/vmware/VMW10_SHFL-SUSE-12.3-64-bit.001/VMW10_SHFL-SUSE-12.3-64-bit.001.vmx nogui

while [ ! -e /home/sgp1000/buildOutput/BootBuildGame.log ]
do
    sleep 30
done

echo " -- Build finished."