#!/bin/sh
# $1 - sandbox
# $2 - gamecore
# $3 - game

SANDBOX="${1}"
GAMECORE="${2}"
GAME="${3}"
NAME="${4}"
IGNORE="-"

#------------------------------------------------------------------------------
echo "------------------------------------------------------------------------------" &>> /gamedev/"${GAME}"_build.log
echo " - makeInstall in sandbox: Sandbox ${SANDBOX}, Gamecore ${GAMECORE}, Game ${GAME}, Name ${NAME}" &>> /gamedev/"${GAME}"_build.log
echo `date +"%Y-%m-%d-%H-%M-%S"` &>> /gamedev/"${GAME}"_build.log

cd /agp/gamecore

#------------------------------------------------------------------------------
echo " - setproj -allgames ..." &>> /gamedev/"${GAME}"_build.log
setproj -allgames &>> /gamedev/"${GAME}"_install.log

#------------------------------------------------------------------------------
echo " - make clean ..." &>> /gamedev/"${GAME}"_build.log
make clean &>> /gamedev/"${GAME}"_install.log

#------------------------------------------------------------------------------
echo " - make install ..." &>> /gamedev/"${GAME}"_build.log
make install &>> /gamedev/"${GAME}"_install.log
INSTALL="${?}"
if [ "${INSTALL}" -gt 0 ]; then
    echo " - make install failed: ${INSTALL}" &>> /gamedev/"${GAME}"_build.log
    exit ${INSTALL}
fi

if [ "${NAME}" = "${IGNORE}" ]; then
    echo " - skipping translation files for ${NAME} ... " &>> /gamedev/"${GAME}"_build.log
else
    echo " - update translation files for ${NAME} ... " &>> /gamedev/"${GAME}"_build.log
    sh /gamedev/gamecore/tools/updateTranslationFiles.sh "${NAME}" &>> /gamedev/"${GAME}"_build.log
    INSTALL="${?}"
    if [ "${INSTALL}" -gt 0 ]; then
        echo " - update translation files failed: ${INSTALL}" &>> /gamedev/"${GAME}"_build.log
        exit ${INSTALL}
    fi
fi
#------------------------------------------------------------------------------
echo " - build finished" &>> /gamedev/"${GAME}"_build.log
echo `date +"%Y-%m-%d-%H-%M-%S"` &>> /gamedev/"${GAME}"_build.log
echo "------------------------------------------------------------------------------" &>> /gamedev/"${GAME}"_build.log

# and return with our exit status from chroot

exit ${INSTALL}
