#!/bin/bash

#------------------------------------------------------------------------------
# set link for shared scripts folder
if [ -e /home/sgp1000/sharedScripts ]; then
    echo " - removing link for shared scripts folder ... "
    sudo rm -f /home/sgp1000/sharedScripts
    #echo $?
fi

echo " - creating link to /home/sgp1000/VBS/Alpha/scripts ... "
sudo ln -sf /home/sgp1000/VBS/Alpha/scripts /home/sgp1000/sharedScripts
#echo $?

#------------------------------------------------------------------------------
# set link for build output folder
if [ -e /home/sgp1000/buildOutput ]; then
    echo " - removing link for build output folder ... "
    sudo rm -rf /home/sgp1000/buildOutput
    #echo $?
fi

if [ ! -e /home/sgp1000/VBS/Alpha/buildOutput ]; then
    mkdir /home/sgp1000/VBS/Alpha/buildOutput
    #echo $?
fi

echo " - creating link to /home/sgp1000/VBS/Alpha/buildOutput ... "
sudo ln -sf /home/sgp1000/VBS/Alpha/buildOutput /home/sgp1000/buildOutput
exit $?

